### PR TITLE
Adjust attribute syntax

### PR DESCRIPTION
**Pull request by jerrywardlow**
Adjust attribute syntax to use a `normal` precedence value to avoid overriding the `default` attributes set in a dependency cookbook. This still allows a project to override values using `override` level precedence.

This attribute/precedence level structure (default -> normal -> override) will be better documented in a Copious Best Practices document in the future once we can agree on a standard way of setting attributes at the project/cookbook/dependent cookbook level.

### CODE REVIEW

**Comment by jerrywardlow** [comment]
@hardyjohnson I agree that makes sense, though in this particular case since we have two different namespaces of attributes (composer and magento::composer), I feel like alphabetical makes more sense.

**Comment by hardyjohnson** [comment]
Does it make sense to break out into two separate files composer.rb and composer-magento.rb?

**Comment by jerrywardlow** [comment]
If we're going to do that we should standardize and have `magento-composer.rb` magento-default.rb` `magento-nginx.rb` `composer.rb` to give a better idea of what's inside

**Comment by hardyjohnson** [comment]
🤷‍♂️ I would be fine w/that as well

**Pull request merged**
